name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.38.5
          cache: true

      - name: Installer les dépendances
        run: flutter pub get

      - name: Analyse statique
        run: flutter analyze

      - name: Tests unitaires
        run: flutter test